language: python
python:
- '3.5'
env:
  matrix:
  - DJANGO_SETTINGS_MODULE=spbgtitoolsbot.settings
  global:
  - secure: "iniTQTHBWvTrRbPC3Z1Dasz/wALxW07aYjWhdoUNgNeFnUaR/NmWrypWuDfArQzAtSRjDFnqPVng2eUAuA36yR5BM51uj2/GCvTpZisXBHBP2WUF2Zt9RFC5x0kf+QuhIGh9WfN5KE8VwBvTNlQemEMr0QoUuDLSY7sLgz83REYZJ6kq+tnGYzHqHKCJbmsaFzV3vBTomToBk8/fMr1G1YIN+f+2NM4dFIHoLIEcOYCe8d4zNatc/93l+/Gia0eegSA7CgKddBJlOMYnkgC4ij5mYgcBY2xlgRlreiyQVBVpE/WUD2n91xpKidE8YYWrh0oOeUhhWOGujZnNSQVY+K+eiEXyAmx2G5QIu4Ca63cWe8Nvy2HW0UTPkC7MG5NTyzYd+1r9rPjV/JgJFQojUvJ7yTwy1NDO41I5emP1K03Q2/c2/tSQQYJgz9cyYPriGyPKJtZ41ltbsdvexzoaaDeMC5x8qXimhqHKbijs6R2dhHn3UghATUOdvPIP1n01r2UF1WQgk1Y2l897NcD8ooUGQJ1flNGNKqTMJ4ISs7/dcD1ULFggNEVmDZ5rbA9Wl3Lw4KBG3ZlvCbiOZnwE/bridvdn+WG0M5SvB0U/dcTwxobjrutzoIgHH49PajdkfPvRyStbNV32HP9R62qn3pyITNr8r+viphbv2OAOgrE="
install: pip install -r requirements.txt
script: python manage.py test
notifications:
  slack: spbgti:DISw2DtYSQ3gQ8jB9NvTbSYG
deploy:
  provider: heroku
  api_key:
    secure: 4c01be97-e60c-4184-be25-b4c3aa2d2fd4
  app: spbgti-tools-bot
  run:
  - sh heroku.sh --app spbgti-tools-bot -staging
  after_deploy:
  - echo "Running integration tests"