language: python
python:
- '3.5.2'
env:
  matrix:
  - DJANGO_SETTINGS_MODULE=spbgtitoolsbot.settings
  global:
  - secure: LU5X5a6jINQCqdlaSCMSnooKPWBV+YGunOnAlSKrZJP5qMvKga6VlseIyUApwguzMzobltyNd5RS/VvjiiMZenq8LO/jCoL5CbIaG63fxa/IXdgria97wne7oHrEMBb/Vv0PIigE8k2vxm6lyqQx5uu78MuMGDMLp6yJhjLYYnDWor5yaRKmcT91kvLzNYaxYhZ5P6GJ30DkIst6tUPdRCKdQa0wIF58rZeeh/ypPVs1feOHTfXGQFGEQmfJsWEBV3gl8bBSQ5HSoAmo1H/wnA6CvdRLfx5T1p3ail+Mn8OhvrwJHwMwZL8TAR/JZDuBBkBFe4356OFMf9gj09zdcFS+FVnjoeAyN95aG4A62iTNrPYjhcTfIu6A9sOcG5JHz/eUKTEVSK6MxCP2dHltDuwRljdCL5pQeUrOVoKEeeqHeUX4w9Sa3XSor0/jWS1O7SZPySgBaLyJrCn0ACcFRbMJ/ccRDQ+ZRQn+R7G/YHD629huPLgwbc0n3sS0hpelYZ/P9PAgPaAJoh8u0AM+ODZ2byMOrm++gcU+T5k1ByTgnerRKfNQ4wXnvc9mqeXM4w1wIE/tqKgz1jB+j1eXt55uW3qbu9QHF4Kqi6Ik6XWFAWdRlZVtNjKtxxN43RjAinb9Lrf1845Eea7SuiSGpynyG9TmilAL5b1Xx7fnYeg=
install: pip install -r requirements.txt
script: echo "Running unit tests"
notifications:
  slack: spbgti:DISw2DtYSQ3gQ8jB9NvTbSYG
deploy:
  provider: heroku
  api_key:
    secure: "JO8wZSeAGlGmgz23bYvRMe/ifL8oSO+BD2zjj24wxjz8PJbZa+X6LhKh63HBabc8E+CVbAa07AuHE4qP4ZGnNOw8Tl2ylnEYrcQkRiBuI1GN3gNDfXDDIoZBrHG2NvWZJ+doXCGt8k9ZCjlNcdvEgAhMq+SKpnEsa8guzyZvAv8F8jIGT2w5BluOwPRy3l0pCSPFbrb3WnMouXqOVhqz8NYQh5uXGBszAtoR3kb8UjIxWEPtsS3aTDplhGrpBTnXClPiygCSRd9rvruoFbqramBfD9JtYVIZEd2wF9RF0moVu2jTziSFv4Pue48y/votZ6UYk60r2h2AoGz2MBeRmalHoFEox5Dqnvwe8HnUjbX0AMhyvMSt+3cL4F7MwINL8+MC3IpWMNjhzk5z0F9Eqr+nXVnfHU11AayeFIhyMXH3C1BlFhVVBP3Pc1pol3l2Bz76zYZUyZJzUW9fhkdtECMpjY2JgKvMRD2y46gjnV+cJmrldvUc9sL3Ymzgvfulh6ESPWcnnIyWcbWOzyoOtpSEl7eLbSq9+W9NYi32WtEJ95ErYorHrpmt8VpurxQV5aFQSUHDZ+n06Qj4A7nzKIh3OV93bMm3CQWGnu/sIxGEoWaLsdv3MQJIBxn0NbCZrG1VoLyOfLBj61iLM3+92vDuogOaN0I8k1bUjF/ARgg="
  app:
    dev: spbgti-tools-bot-staging
    master: spbgti-tools-bot
  run:
    dev:
      - sh heroku.sh --app spbgti-tools-bot-staging
    master:
      - sh heroku.sh --app spbgti-tools-bot
  after_deploy:
  - echo "Running integration tests"
