language: python
python:
- '3.5'
env:
  matrix:
  - DJANGO_SETTINGS_MODULE=spbgtitoolsbot.settings
  global:
  - secure: LU5X5a6jINQCqdlaSCMSnooKPWBV+YGunOnAlSKrZJP5qMvKga6VlseIyUApwguzMzobltyNd5RS/VvjiiMZenq8LO/jCoL5CbIaG63fxa/IXdgria97wne7oHrEMBb/Vv0PIigE8k2vxm6lyqQx5uu78MuMGDMLp6yJhjLYYnDWor5yaRKmcT91kvLzNYaxYhZ5P6GJ30DkIst6tUPdRCKdQa0wIF58rZeeh/ypPVs1feOHTfXGQFGEQmfJsWEBV3gl8bBSQ5HSoAmo1H/wnA6CvdRLfx5T1p3ail+Mn8OhvrwJHwMwZL8TAR/JZDuBBkBFe4356OFMf9gj09zdcFS+FVnjoeAyN95aG4A62iTNrPYjhcTfIu6A9sOcG5JHz/eUKTEVSK6MxCP2dHltDuwRljdCL5pQeUrOVoKEeeqHeUX4w9Sa3XSor0/jWS1O7SZPySgBaLyJrCn0ACcFRbMJ/ccRDQ+ZRQn+R7G/YHD629huPLgwbc0n3sS0hpelYZ/P9PAgPaAJoh8u0AM+ODZ2byMOrm++gcU+T5k1ByTgnerRKfNQ4wXnvc9mqeXM4w1wIE/tqKgz1jB+j1eXt55uW3qbu9QHF4Kqi6Ik6XWFAWdRlZVtNjKtxxN43RjAinb9Lrf1845Eea7SuiSGpynyG9TmilAL5b1Xx7fnYeg=
install: pip install -r requirements.txt
script: python manage.py test
notifications:
  slack: spbgti:DISw2DtYSQ3gQ8jB9NvTbSYG
deploy:
  provider: heroku
  api_key:
    secure: 4c01be97-e60c-4184-be25-b4c3aa2d2fd4
  app: spbgti-tools-bot
  run:
  - sh heroku.sh --app spbgti-tools-bot -staging
  after_deploy:
  - echo "Running integration tests"
