language: python
python:
- '3.5'
env:
  matrix:
  - DJANGO_SETTINGS_MODULE=spbgtitoolsbot.settings
  global:
    secure: O7C4FYrORaPXrpOyvL7vBHsw+yL5764bZpySGfmXAYKfOhBNHGz3epJAoOdl/HQ+YV4VOqU3dpQziLnxTaK5LjZnM5dLPk39BnXMCjCevDD9+L48uTczKA4b2PFQCyqcNxHJkeAXU7wREUG4rNyS9zVEZTJP2rKRug1wGGf90keVmmlQXrZv7DokNHH20QqJSzF3Mkvud7kVTNY5RgM6lcsOrMqbJk9a5t+DyM1K+98jFznQEg3A3MIxURSpADWPGOiu97rziIvP1UvgjMiA1/SVojQqjJGlTKN98ajSmR9C0ieXxg4rDuIOt+6Xt33tskCIHrlOsgAUP0DJowpPGTLDl3DX/uqpTYVD/GuKYbLBGfVO5tHq1jUDI2nIAMDM7t+KQR07x7IjS95tAivXaTx61Pk57UNg71EmRjz8UYXRBX9r9uqQw4gLcHbc7FY3XZ8li77eRbej+2j00nbXdXc+Jgbg1G8iJ8vbzeM4HqEhGCQMM9e/NMr/+QaRndeI2NveOB8jRhJzjyQxa8WZVVDNKcf61qW3hkRI18UxMtKMdDF1JOsh5MB9g+L6jqa8Q5vr3914I6EpdBv0AgBKe8u2GLDHkZX7uDEKAwt6czcilMX08zjiiwbbA/T3Dd32Lb1M8hT3CQ9YzRFkuzrlz5BfEMrVMs0D7aNfo5cjNYE=
install: pip install -r requirements.txt
script: python manage.py test
notifications:
  slack: spbgti:DISw2DtYSQ3gQ8jB9NvTbSYG
deploy:
  provider: heroku
  api_key:
    secure: 4c01be97-e60c-4184-be25-b4c3aa2d2fd4
  app: spbgti-tools-bot
  run:
  - sh heroku.sh --app spbgti-tools-bot -staging
  after_deploy:
  - echo "Running integration tests"
